### ISSUE TITLE
Error on initialisation

### ISSUE THREAD

**Issue by simonwibberley** [idmc-labs/idetect#64]
Hi there,

I'm attempting to install an instance of this; however, when running `docker-compose up workers`, the below error occurs, which seems to indicate a version problem with numpy. I tried changing the version to `NumPy==1.16.3` in `docker/idetect/Dockerfile` however this resulted in the same error.

System info:
`Ubuntu 18.04.1 LTS`
`Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`Docker version 18.06.1-ce, build e68fc7a`

Any thoughts / guidance greatly appreciated! Many thanks.
 
```
$ docker-compose up workers
Starting idetect_localdb_1 ... 
Starting idetect_localdb_1 ... done
Recreating idetect_workers_1 ... 
Recreating idetect_workers_1 ... done
Attaching to idetect_workers_1
workers_1    | Traceback (most recent call last):
workers_1    |   File "python/setup.py", line 12, in <module>
workers_1    |     from idetect.nlp_models.category import *
workers_1    |   File "/home/idetect/python/idetect/nlp_models/category.py", line 1, in <module>
workers_1    |     import gensim
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/gensim/__init__.py", line 6, in <module>
workers_1    |     from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/gensim/models/__init__.py", line 7, in <module>
workers_1    |     from .coherencemodel import CoherenceModel
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/gensim/models/coherencemodel.py", line 30, in <module>
workers_1    |     from gensim.models.wrappers import LdaVowpalWabbit, LdaMallet
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/gensim/models/wrappers/__init__.py", line 8, in <module>
workers_1    |     from .fasttext import FastText
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/gensim/models/wrappers/fasttext.py", line 38, in <module>
workers_1    |     from gensim.models.keyedvectors import KeyedVectors, Vocab
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/gensim/models/keyedvectors.py", line 67, in <module>
workers_1    |     from pyemd import emd
workers_1    |   File "/usr/local/lib/python3.6/dist-packages/pyemd/__init__.py", line 75, in <module>
workers_1    |     from .emd import emd, emd_with_flow, emd_samples
workers_1    |   File "__init__.pxd", line 885, in init pyemd.emd
workers_1    | ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
idetect_workers_1 exited with code 1
```

**Comment by WanderingStar** [comment]
There are pickled NLP models that will probably need to be recreated if you change the NumPy version. @georgerichardson might be able to give quick tips to help on that.

**Comment by simonwibberley** [comment]
@WanderingStar Hi! Thanks for your response - just to clarify though, I didn't change the numpy version initially, but only in an attempt to fix the error.

**Comment by WanderingStar** [comment]
Odd. It's been months since I did any work on this, and a while since I tried to build it from scratch. I can try to take a look tonight, but maybe @milanoleonardo has more recent experience with it.

**Comment by milanoleonardo** [comment]
mmmh that's new to me. I just tried and I have the same error.

**Comment by WanderingStar** [comment]
Please `git pull` master, rerun `docker-compose build` and try again. Installing NumPy separately first fixes it for me.

**Comment by milanoleonardo** [comment]
That works, thanks a loot @WanderingStar !

**Comment by simonwibberley** [comment]
Thanks @WanderingStar  !
